export const fieldTypeOptions = [
    { value: 'text', label: 'Text' },
    { value: 'textarea', label: 'Textarea' },
    { value: 'email', label: 'Email' },
    { value: 'password', label: 'Password' },
    { value: 'url', label: 'URL' },
    { value: 'tel', label: 'Telephone' },
    { value: 'number', label: 'Number' },
    { value: 'select', label: 'Select' },
    { value: 'checkbox', label: 'Checkbox' },
    { value: 'radio', label: 'Radio' },
    { value: 'date', label: 'Date' },
    { value: 'datetime-local', label: 'Date and Time' },
    { value: 'time', label: 'Time' },
    { value: 'month', label: 'Month' },
    { value: 'week', label: 'Week' },
    { value: 'file', label: 'File Upload' },
    { value: 'color', label: 'Color Picker' },
    { value: 'hidden', label: 'Hidden' },
];

export const platformOptions = [
    { value: 'facebook', label: 'Facebook' },
    { value: 'twitter', label: 'Twitter' },
    { value: 'linkedin', label: 'LinkedIn' },
    { value: 'instagram', label: 'Instagram' },
    { value: 'whatsapp', label: 'WhatsApp' },
    { value: 'youtube', label: 'YouTube' },
    { value: 'telegram', label: 'Telegram' },
    { value: 'website', label: 'Website' },
    { value: 'other', label: 'Other' },
];

export const fontFamilyOptions = [
    { value: "Inter, sans-serif", label: "Inter (Default)" },
    { value: "Roboto, sans-serif", label: "Roboto" },
    { value: "Open Sans, sans-serif", label: "Open Sans" },
    { value: "Poppins, sans-serif", label: "Poppins" },
    { value: "Lato, sans-serif", label: "Lato" },
    { value: "Montserrat, sans-serif", label: "Montserrat" },
    { value: "Source Sans Pro, sans-serif", label: "Source Sans Pro" },
    { value: "Noto Sans, sans-serif", label: "Noto Sans" },
    { value: "Rubik, sans-serif", label: "Rubik" },
    { value: "Nunito, sans-serif", label: "Nunito" },
    { value: "Work Sans, sans-serif", label: "Work Sans" },
    { value: "Mulish, sans-serif", label: "Mulish" },
    { value: "Manrope, sans-serif", label: "Manrope" },
    { value: "Raleway, sans-serif", label: "Raleway" },
    { value: "IBM Plex Sans, sans-serif", label: "IBM Plex Sans" },
    { value: "DM Sans, sans-serif", label: "DM Sans" },
    { value: "Quicksand, sans-serif", label: "Quicksand" },
    { value: "Space Grotesk, sans-serif", label: "Space Grotesk" },
    { value: "Karla, sans-serif", label: "Karla" },
    { value: "Fira Sans, sans-serif", label: "Fira Sans" },
    { value: "Asap, sans-serif", label: "Asap" },
    { value: "Titillium Web, sans-serif", label: "Titillium Web" },
    { value: "Cabin, sans-serif", label: "Cabin" },
    { value: "Exo 2, sans-serif", label: "Exo 2" },
    { value: "Barlow, sans-serif", label: "Barlow" },
    { value: "Signika, sans-serif", label: "Signika" },
    { value: "PT Sans, sans-serif", label: "PT Sans" },
    { value: "Oxygen, sans-serif", label: "Oxygen" },
    { value: "Questrial, sans-serif", label: "Questrial" },
    { value: "Urbanist, sans-serif", label: "Urbanist" },
    { value: "Be Vietnam Pro, sans-serif", label: "Be Vietnam Pro" },
    { value: "Public Sans, sans-serif", label: "Public Sans" },
    { value: "Hind, sans-serif", label: "Hind" },
    { value: "Figtree, sans-serif", label: "Figtree" },
    { value: "Plus Jakarta Sans, sans-serif", label: "Plus Jakarta Sans" },
    { value: "Sora, sans-serif", label: "Sora" },
    { value: "Epilogue, sans-serif", label: "Epilogue" },
    { value: "Red Hat Display, sans-serif", label: "Red Hat Display" },
    { value: "Lexend, sans-serif", label: "Lexend" },
    { value: "Outfit, sans-serif", label: "Outfit" },
    { value: "Overpass, sans-serif", label: "Overpass" },
    { value: "Jost, sans-serif", label: "Jost" },
    { value: "Archivo, sans-serif", label: "Archivo" },
    { value: "Syne, sans-serif", label: "Syne" },
    { value: "Chivo, sans-serif", label: "Chivo" },
    { value: "Familjen Grotesk, sans-serif", label: "Familjen Grotesk" },
    { value: "Hubot Sans, sans-serif", label: "Hubot Sans" },
    { value: "Gabarito, sans-serif", label: "Gabarito" },
    { value: "Geist, sans-serif", label: "Geist" },
    { value: "League Spartan, sans-serif", label: "League Spartan" },
    { value: "Space Mono, sans-serif", label: "Space Mono" },
    { value: "Anybody, sans-serif", label: "Anybody" },
    { value: "Instrument Sans, sans-serif", label: "Instrument Sans" },
    { value: "Spline Sans, sans-serif", label: "Spline Sans" },
    { value: "Cabinet Grotesk, sans-serif", label: "Cabinet Grotesk" },
    { value: "Switzer, sans-serif", label: "Switzer" },
    { value: "Clash Display, sans-serif", label: "Clash Display" },
    { value: "General Sans, sans-serif", label: "General Sans" },
    { value: "Supreme, sans-serif", label: "Supreme" },
    { value: "Wix Madefor Display, sans-serif", label: "Wix Madefor Display" },
    { value: "Pilcrow Rounded, sans-serif", label: "Pilcrow Rounded" },
    { value: "Fragment Mono, sans-serif", label: "Fragment Mono" },
    { value: "Darker Grotesque, sans-serif", label: "Darker Grotesque" },
    { value: "Jakarta, sans-serif", label: "Jakarta" },
    { value: "Satoshi, sans-serif", label: "Satoshi" },
    { value: "Trirong, sans-serif", label: "Trirong" },
    { value: "Azeret Mono, sans-serif", label: "Azeret Mono" },
    { value: "Newsreader, sans-serif", label: "Newsreader" },
    { value: "Fraunces, sans-serif", label: "Fraunces" },
    { value: "Commissioner, sans-serif", label: "Commissioner" },
    { value: "Encode Sans, sans-serif", label: "Encode Sans" },
    { value: "Atkinson Hyperlegible, sans-serif", label: "Atkinson Hyperlegible" },
    { value: "Gudea, sans-serif", label: "Gudea" },
    { value: "M PLUS 1p, sans-serif", label: "M PLUS 1p" },
    { value: "M PLUS Rounded 1c, sans-serif", label: "M PLUS Rounded 1c" },
    { value: "Noto Sans JP, sans-serif", label: "Noto Sans JP" },
    { value: "Noto Sans KR, sans-serif", label: "Noto Sans KR" },
    { value: "Noto Sans SC, sans-serif", label: "Noto Sans SC" },
    { value: "Noto Sans TC, sans-serif", label: "Noto Sans TC" },
    { value: "Yantramanav, sans-serif", label: "Yantramanav" },
    { value: "Hanken Grotesk, sans-serif", label: "Hanken Grotesk" },
    { value: "Comfortaa, sans-serif", label: "Comfortaa" },
    { value: "Varela Round, sans-serif", label: "Varela Round" },
    { value: "Alata, sans-serif", label: "Alata" },
    { value: "Josefin Sans, sans-serif", label: "Josefin Sans" },
    { value: "Alegreya Sans, sans-serif", label: "Alegreya Sans" },
    { value: "Cantarell, sans-serif", label: "Cantarell" },
    { value: "Dosis, sans-serif", label: "Dosis" },
    { value: "Abel, sans-serif", label: "Abel" },
    { value: "Didact Gothic, sans-serif", label: "Didact Gothic" },
    { value: "Andika, sans-serif", label: "Andika" },
    { value: "Arimo, sans-serif", label: "Arimo" },
    { value: "Tinos, sans-serif", label: "Tinos" },
    { value: "Cormorant, sans-serif", label: "Cormorant" },
    { value: "Proza Libre, sans-serif", label: "Proza Libre" },
    { value: "Sarabun, sans-serif", label: "Sarabun" },
    { value: "Athiti, sans-serif", label: "Athiti" },
    { value: "Prompt, sans-serif", label: "Prompt" },
    { value: "Mitr, sans-serif", label: "Mitr" },
    { value: "Chakra Petch, sans-serif", label: "Chakra Petch" },
    { value: "K2D, sans-serif", label: "K2D" },
    { value: "Niramit, sans-serif", label: "Niramit" },
    { value: "Srisakdi, sans-serif", label: "Srisakdi" },
    { value: "Thasadith, sans-serif", label: "Thasadith" }
];