import React from "react";
import DataTable from "@components/DataTable.jsx";
import Avatar from "@components/Avatar.jsx";
import {formatDate} from "@helpers/dateTime.js";
import {toTitleCase} from "@helpers/formatters.js";

const ReplenishmentHistory = () => {

    const columns = [
        {
            Header: 'File',
            Cell: ({ row }) => (
                <div className="ti-btn ti-btn-primary-full m-2">
                    {row.original.file_url ? (
                        <a
                            href={row.original.file_url}
                            download
                        >
                            <i className="ri-file-download-line text-[1rem]"></i>
                        </a>
                    ) : (
                        <span className="text-gray-500">No File</span>
                    )}
                </div>
            )
        },
        {
            Header: 'Forecast Days',
            accessor: 'forecast_days',
            Cell: ({ value }) => <span>{value || 'N/A'}</span>
        },
        {
            Header: 'Total Warehouses',
            accessor: 'total_warehouses',
            Cell: ({ value }) => <span>{value || 'N/A'}</span>
        },
        {
            Header: 'Total Items',
            accessor: 'total_items',
            Cell: ({ value }) => <span>{value || 'N/A'}</span>
        },
        {
            Header: 'Forecast Method',
            accessor: 'forecast_method',
            Cell: ({ value }) => <span>{ toTitleCase(value) }</span>
        },
        {
            Header: 'Standard Deviations',
            accessor: 'standard_deviations',
            Cell: ({ value }) => <span>{ value }</span>
        },
        {
            Header: 'Sale Date Range',
            Cell: ({ row }) => (<span> {`${formatDate(row.original.from_date)} - ${formatDate(row.original.to_date)}`}</span>)
        },
        {
            Header: 'Generated By',
            Cell: ({ row }) => (
                <div className="flex items-center">
                    <Avatar
                        avatar={row.original.created_by.avatar ? row.original.created_by.avatar : null}
                        full_name={row.original.created_by?.full_name || 'N/A'}
                        size='sm'
                        parentClasses='bg-primary/10 !fill-primary'
                    />
                    <div className='ms-2'>
                        <p className="font-semibold mb-0 flex items-center">
                            {row.original.created_by.full_name || 'N/A'}
                        </p>
                    </div>
                </div>
            )
        },
        {
            Header: 'Generated At',
            accessor: 'created_at',
            Cell: ({ value }) => <span>{formatDate(value, 'MMM dd, yyyy - HH:mm') || 'N/A'}</span>
        }
    ];
  return (
      <>
          <DataTable
              columns={columns}
              title="Report History"
              apiUrl="/scm/report/history/"
          />
      </>
  )
}

export default ReplenishmentHistory